site_name: OctopusLab
nav:
  - Úvod: index.md
  - Základní dokumentace: basicdoc.md
  - Projekty: projects.md
  - 'Vybrané projekty': 
      - 'Projekt 1': project1.md
      - 'Projekt 2': project2.md
  - 'Workshopy / tutoriály':
      - 'Tut 1': tut1.md
      - 'Tut 1': tut1.md

theme: readthedocs

markdown_extensions:
  - attr_list
